Feacure/g khyzhynska/crud frontend
CodeGeneration-2020/CGS-test-camp-task pull request #107
Opened 2021-09-27 06:51 UTC by Gal4enock

CRUD operations for mobile, types, for TS, screens

2021-09-27 08:01 UTC, CodeGeneration-2020 requested changes
- Please avoid inline-function all over the app. Everything should be named
- please do proper spacings all over the app. I showed you a few examples
- avoid mistakes in english words

2021-09-27 08:01 UTC, CodeGeneration-2020 commented on mobile/screen/auth/StartPage.tsx
> +        onPress={() => navigation.navigate('TodoList') } >
inline function

2021-09-27 08:01 UTC, CodeGeneration-2020 commented on mobile/screen/auth/StartPage.tsx
> +        onPress={() => navigation.navigate('TodoList') } >
inline function

2021-09-27 08:01 UTC, CodeGeneration-2020 commented on mobile/services/TodoModel.ts
> +export { createTodoModel };
please do line-break below

2021-09-27 08:13 UTC, Gal4enock commented on mobile/screen/auth/LoginScreen.tsx
> +            <Button onPress={() => handleSubmit()} title="Submit" />
this component is developing still.. and i had an error, writing this function like: onPress={handleSubmit}

2021-09-27 08:14 UTC, Gal4enock commented on mobile/screen/auth/RegisterScreen.tsx
> +            <Button onPress={() => handleSubmit()} title="Submit" />
this component is developing still.. and i had an error, writing this function like: onPress={handleSubmit}

2021-09-27 08:19 UTC, closed without merging

2021-09-28 10:43 UTC, Gal4enock commented on mobile/App.tsx
> +
fixed in another pull request

2021-09-28 10:43 UTC, Gal4enock commented on mobile/App.tsx
> +          }} name="StartPage" component={ StartPage }/>
fixed in another pull request

2021-09-28 10:43 UTC, Gal4enock commented on mobile/App.tsx
> +          <Stack.Screen options={{
fixed in another pull request

2021-09-28 10:43 UTC, Gal4enock commented on mobile/components/EditTodo.tsx
> +        {({ handleChange,
fixed in another pull request

2021-09-28 10:44 UTC, Gal4enock commented on mobile/screen/auth/RegisterScreen.tsx
> +            <Button onPress={() => handleSubmit()} title="Submit" />
we've spoke about it

2021-09-28 10:47 UTC, Gal4enock commented on mobile/App.tsx
> +    // alignItems: 'center',
fixed in another pull request

2021-09-28 15:20 UTC, Gal4enock commented on mobile/components/EditTodo.tsx
> +            <Button onPress={() => handleSubmit()} title="Edit" />
fixed in another pull request

2021-09-28 15:20 UTC, Gal4enock commented on mobile/components/TodoElement.tsx
> +import {
fixed in another pull request

2021-09-28 15:20 UTC, Gal4enock commented on mobile/components/TodoElement.tsx
> +        {({ handleChange,
fixed in another pull request

2021-09-28 15:20 UTC, Gal4enock commented on mobile/components/TodoElement.tsx
> +};
fixed in another pull request

2021-09-28 15:20 UTC, Gal4enock commented on mobile/components/TodoList.tsx
> +const Item = ({ title, _id, description, year,
fixed in another pull request

2021-09-28 15:20 UTC, Gal4enock commented on mobile/components/TodoList.tsx
> +    console.log(todoList);
fixed in another pull request

2021-09-28 15:21 UTC, Gal4enock commented on mobile/components/TodoList.tsx
> +  const renderItem = ({ item }) => (
fixed in another pull request

2021-09-28 15:21 UTC, Gal4enock commented on mobile/components/TodoList.tsx
> +        onPress={() => {
fixed in another pull request

2021-09-28 15:21 UTC, Gal4enock commented on mobile/components/TodoList.tsx
> +  const renderItem = ({ item }) => (
fixed in another pull request

2021-09-28 15:22 UTC, Gal4enock commented on mobile/screen/auth/LoginScreen.tsx
> +            <Button onPress={() => handleSubmit()} title="Submit" />
fixed in another pull request

2021-09-28 15:22 UTC, Gal4enock commented on mobile/screen/auth/StartPage.tsx
> +        onPress={() => navigation.navigate('TodoList') } >
fixed in another pull request

2021-09-28 15:23 UTC, Gal4enock commented on mobile/screen/auth/StartPage.tsx
> +        onPress={() => navigation.navigate('TodoList') } >
fixed in another pull request

2021-09-28 15:23 UTC, Gal4enock commented on mobile/services/TodoModel.ts
> +export { createTodoModel };
fixed in another pull request

2021-09-28 15:26 UTC, Gal4enock commented
please, check pull https://github.com/CodeGeneration-2020/CGS-test-camp-task/pull/109