Feat: auth backend
CodeGeneration-2020/CGS-test-camp-task pull request #117
Opened 2021-09-28 12:14 UTC by murinus007

2021-09-29 10:44 UTC, CodeGeneration-2020 requested changes

2021-09-29 14:51 UTC, CodeGeneration-2020 requested changes

2021-09-29 14:51 UTC, CodeGeneration-2020 commented on server/src/controllers/auth.controller.ts
> +      if (err) {
Дублирование кода

2021-09-29 14:51 UTC, CodeGeneration-2020 commented on server/src/controllers/auth.controller.ts
> +        return res.status(401).json({ status: 'error', code: 'unauthorized' })
Дублирование кода

2021-09-29 14:51 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +    const token = req.headers.authorization.replace('Bearer ', '');
Создай лучше auth serivce и вынеси туда эту логику

2021-09-30 09:47 UTC, murinus007 commented on server/src/controllers/todo.controller.ts
> +    const token = req.headers.authorization.replace('Bearer ', '');
создал auth serivce

2021-09-30 11:28 UTC, CodeGeneration-2020 approved these changes

2021-09-30 11:47 UTC, merged