Implement todo
CodeGeneration-2020/CGS-test-camp-task pull request #16
Opened 2021-11-24 22:29 UTC by anlithov

Live Todo list. Pages. Add todo module

2021-11-26 11:01 UTC, CodeGeneration-2020 requested changes

2021-11-26 11:01 UTC, CodeGeneration-2020 commented on mobile/src/screens/TodoStack/components/forms/TodoElement.tsx
> +    console.log('Start Mutate');
Remove logs

2021-11-26 11:01 UTC, CodeGeneration-2020 commented on mobile/src/screens/TodoStack/components/forms/TodoElement.tsx
> +  const navigation = useNavigation<any>();
any

2021-11-26 11:01 UTC, CodeGeneration-2020 commented on mobile/src/screens/TodoStack/components/forms/TodoElement.tsx
> +interface TodoElementProps {
Interfaces should start with I letter

2021-11-26 11:01 UTC, CodeGeneration-2020 commented on mobile/src/service/todo.service.ts
> +export class TodoService {
Create base service example of it you can find in our styleguide

2021-11-26 20:29 UTC, anlithov commented on mobile/src/service/todo.service.ts
> +export class TodoService {
Don't understand the issue. Tried to make service according to styles with some minor changes.
What do I need to fix exactly?

2021-11-28 22:06 UTC, anlithov commented on mobile/src/service/todo.service.ts
> +export class TodoService {
Done. Found guide. Implemented http service and rebuilt of todo service in last commit

2021-11-29 11:15 UTC, merged