feat: implement_basic_backend_structure_for_crud_operations
CodeGeneration-2020/CGS-test-camp-task pull request #24
Opened 2021-11-30 16:08 UTC by 13dds13

2021-12-01 07:26 UTC, CodeGeneration-2020 requested changes

2021-12-01 07:26 UTC, CodeGeneration-2020 commented on server/.env
> +HOST=
Do not push env variables

2021-12-01 07:26 UTC, CodeGeneration-2020 commented on server/src/models/User.ts
> +  token: {
Token should not be stored in db

2021-12-01 07:26 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +    async updateTodo(_: Request, res: Response) {
add joi Validation

2021-12-01 07:26 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +    async addTodo(_: Request, res: Response) {
add joi Validation

2021-12-01 07:26 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +    async deleteTodo(_: Request, res: Response) {
Existance validation

2021-12-01 07:26 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +        try {
1. Try/catch logic dublicates
2.  Catch should format propper error with to the client istead of just logging that

2021-12-01 07:26 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +        try {
Add try/catch wrapper function

2021-12-01 07:26 UTC, CodeGeneration-2020 commented on server/src/services/todo.service.ts
> +        return "Todo successfully added";
Where is real logic ?

2021-12-01 07:26 UTC, CodeGeneration-2020 commented on server/src/services/user.service.ts
> +  }
Where is real logic ?

2021-12-01 07:26 UTC, CodeGeneration-2020 commented on server/src/server.ts
> +import dotenv from "dotenv";
Why do you have two main files ?

2021-12-01 07:26 UTC, CodeGeneration-2020 commented on server/src/app.ts
> +
What is that ?

2021-12-03 08:10 UTC, 13dds13 commented on server/.env
> +HOST=
fixed

2021-12-03 08:11 UTC, 13dds13 commented on server/src/controllers/todo.controller.ts
> +    async updateTodo(_: Request, res: Response) {
fixed

2021-12-03 08:11 UTC, 13dds13 commented on server/src/controllers/todo.controller.ts
> +    async addTodo(_: Request, res: Response) {
fixed

2021-12-03 08:11 UTC, 13dds13 commented on server/src/controllers/todo.controller.ts
> +    async deleteTodo(_: Request, res: Response) {
fixed

2021-12-03 08:11 UTC, 13dds13 commented on server/src/controllers/todo.controller.ts
> +        try {
fixed

2021-12-03 08:11 UTC, 13dds13 commented on server/src/services/todo.service.ts
> +        return "Todo successfully added";
fixed

2021-12-03 08:11 UTC, 13dds13 commented on server/src/services/user.service.ts
> +  }
fixed

2021-12-03 08:11 UTC, 13dds13 commented on server/src/server.ts
> +import dotenv from "dotenv";
fixed

2021-12-03 08:12 UTC, 13dds13 commented on server/src/app.ts
> +
fixed

2021-12-03 08:36 UTC, CodeGeneration-2020 requested changes

2021-12-03 08:36 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +        const { priority, done, date, topic } = savedTodo;
я думаю тут проще исключить то что тебе не нужно
И можешь res.send вынести внутрь `tryCatchWrapper `,
зачем тебе второй параметр в tryCatchWrapper ?

2021-12-03 08:36 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +        todo ? res.send(todo) : res.send({ message: "Such todo didn't find" });
Откуда ты знаешь что тебе вернет именно 404 ошибку ?
Напиши отдельную функцию на проверку isExist, можешь сделать это мидлваром

2021-12-03 08:36 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +        todo ? res.send(todo) : res.send({ message: "Such todo didn't find" });
Откуда ты знаешь что тебе вернет именно 404 ошибку ?
Напиши отдельную функцию на проверку isExist, можешь сделать это мидлваром

2021-12-03 08:36 UTC, CodeGeneration-2020 commented on server/src/controllers/user.controller.ts
> +import createAuthToken from "../services/helpers/createAuthToken";
Должен быть внутри authService класса

2021-12-03 08:36 UTC, CodeGeneration-2020 commented on server/src/middlewares/checkReqBody.ts
> +    baseUrl.includes("todos") ? validationSchema = todoSchema : validationSchema = userSchema;
Не привязывайся конкретно к туду или юзеру, если у тебя будет не 2 модели в приложении ?
Можешь использовать замыкание

2021-12-03 08:36 UTC, CodeGeneration-2020 commented on server/src/models/User.ts
> +userSchema.methods.setPassword = function (password: string) {
Вынеси в AuthSerivce не реализуй логику в моделе

2021-12-03 08:36 UTC, CodeGeneration-2020 commented on server/src/models/User.ts
> +userSchema.methods.validPassword = function (password: string) {
Вынеси в AuthSerivce не реализуй логику в моделе

2021-12-03 08:36 UTC, CodeGeneration-2020 commented on server/src/services/createDefaultAvatar.ts
> +const createDefaultAvatar = (userEmail: string) =>
UserService method

2021-12-03 08:36 UTC, CodeGeneration-2020 commented on server/src/services/helpers/createAuthToken.ts
> +const createAuthToken = (data: {}) => {
AuthService method

2021-12-03 08:36 UTC, CodeGeneration-2020 commented on server/src/services/todo.service.ts
> +    async updateTodoById(data: {}) {
Неправильные типы во всем сервисе `data: {}`

2021-12-03 08:36 UTC, CodeGeneration-2020 commented on server/src/services/user.service.ts
> +  async createUser(data: {}) {
Типы

2021-12-03 15:59 UTC, 13dds13 commented on server/src/middlewares/checkReqBody.ts
> +    baseUrl.includes("todos") ? validationSchema = todoSchema : validationSchema = userSchema;
in progress

2021-12-03 17:13 UTC, CodeGeneration-2020 requested changes

2021-12-03 17:13 UTC, CodeGeneration-2020 commented on server/src/middlewares/asyncWrapper.ts
> +            next(error);
Ты выбрасываешь эрор на клиент ?

2021-12-03 17:13 UTC, CodeGeneration-2020 commented on server/src/middlewares/isExist.ts
> +    todo ? next() : res.status(401).send({ message: "Such todo didn't find" });
Не должно привязываться к туду

2021-12-03 17:13 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +        res.send(todo);
ты можешь возвращать туду из функции а res.send делать в враппере

2021-12-03 17:13 UTC, CodeGeneration-2020 commented on server/src/services/auth.service.ts
> +    setPassword = function (password: string) {
Не используй обычные функции в классе

2021-12-03 17:13 UTC, CodeGeneration-2020 commented on server/src/services/auth.service.ts
> +dotenv.config();
лишний энв конфиг

2021-12-05 09:00 UTC, 13dds13 commented on server/src/services/auth.service.ts
> +dotenv.config();
fixed

2021-12-05 09:02 UTC, 13dds13 commented on server/src/services/auth.service.ts
> +    setPassword = function (password: string) {
It was not me, I was set up))

2021-12-05 10:24 UTC, 13dds13 commented on server/src/controllers/todo.controller.ts
> +        res.send(todo);
fixed

2021-12-06 08:58 UTC, 13dds13 commented on server/src/middlewares/checkReqBody.ts
> +    baseUrl.includes("todos") ? validationSchema = todoSchema : validationSchema = userSchema;
done

2021-12-06 08:58 UTC, 13dds13 commented on server/src/middlewares/isExist.ts
> +    todo ? next() : res.status(401).send({ message: "Such todo didn't find" });
done

2021-12-06 11:38 UTC, CodeGeneration-2020 approved these changes

2021-12-06 11:38 UTC, merged