feat: home screen navigation
CodeGeneration-2020/CGS-test-camp-task pull request #27
Opened 2021-12-06 18:25 UTC by 13dds13

2021-12-07 06:39 UTC, CodeGeneration-2020 requested changes

2021-12-07 06:39 UTC, CodeGeneration-2020 commented on mobile/.eslintrc.json
> -    "env": {
Do not delete that !!!

2021-12-07 06:39 UTC, CodeGeneration-2020 commented on mobile/README.md
> -2. Install `Expo mobile app`: [Android](https://play.google.com/store/apps/details?id=host.exp.exponent) or [IOS](https://search.itunes.apple.com/WebObjects/MZContentLink.woa/wa/link?path=apps%2fexpo
DO NOT DELETE THAT

2021-12-07 06:39 UTC, CodeGeneration-2020 commented on mobile/README.md
> -2. Install `Expo mobile app`: [Android](https://play.google.com/store/apps/details?id=host.exp.exponent) or [IOS](https://search.itunes.apple.com/WebObjects/MZContentLink.woa/wa/link?path=apps%2fexpo
USE yarn isntead of npm

2021-12-07 06:39 UTC, CodeGeneration-2020 commented on mobile/package.json
> +    "@react-navigation/native": "^6.0.6",
Why you reinstalled dependencies ?

2021-12-07 06:39 UTC, CodeGeneration-2020 commented on mobile/src/components/authBtn/AuthBtn.tsx
> +        borderColor: "#6495ed",
Move to `theme const`

2021-12-07 06:39 UTC, CodeGeneration-2020 commented on mobile/src/components/authBtn/AuthBtn.tsx
> +        color: "#483d8b"
Move to theme const

2021-12-07 06:39 UTC, CodeGeneration-2020 commented on mobile/src/components/authBtn/AuthBtn.tsx
> +        fontSize: 16,
Move to theme const

2021-12-07 06:39 UTC, CodeGeneration-2020 commented on mobile/src/components/authBtn/AuthBtn.tsx
> +        marginBottom: 16,
Move to theme const

2021-12-07 06:39 UTC, CodeGeneration-2020 commented on mobile/src/screens/HomeScreen.tsx
> +        fontSize: 24,
Move to theme const

2021-12-07 06:39 UTC, CodeGeneration-2020 commented on mobile/src/screens/HomeScreen.tsx
> +        color: "#483d8b"
Move to theme const

2021-12-07 06:39 UTC, CodeGeneration-2020 commented on mobile/src/screens/HomeScreen.tsx
> +        marginBottom: 16,
Move to theme const

2021-12-07 06:39 UTC, CodeGeneration-2020 commented on mobile/tsconfig.json
> -    "jsx": "react",
????

2021-12-08 14:11 UTC, CodeGeneration-2020 requested changes

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/components/todoForm/TodoForm.tsx
> +          {errors.description && touched.description ? (
Code  dublicates, move Title, input and error message to separate component `AppInput`

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/components/todoForm/TodoForm.tsx
> +            onValueChange={handleChange('priority')}
Code duplicates, move to components.

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/components/todoList/TodoList.tsx
> +    const { data } = useQuery('todos', apiTodosServices.getAllTodos);
You can move `todo` into `const` to avoid misspells. `app-urls.ts`

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/components/todoList/todoItem/TodoItem.tsx
> +            queryClient.invalidateQueries('deletedTodo');
Const

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/screens/CreateTodoScreen.tsx
> +            queryClient.invalidateQueries('newTodo');
Const

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/screens/EditTodoScreen.tsx
> +            queryClient.invalidateQueries('updatedTodo');
Const

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/screens/LoginScreen.tsx
> +            queryClient.invalidateQueries('authUser');
Const, and maybe call it `user`

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/screens/LoginScreen.tsx
> +                        <TextInput
Shared input

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/screens/RegisterScreen.tsx
> +                        <TextInput
Inputs

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/services/apiTodosServices.tsx
> +import { endpoint } from "../../data/api/db.json"
DO NOT use axios directly, check our `codestyle` and create base serivce for inteructions with API

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/services/apiTodosServices.tsx
> +import { endpoint } from "../../data/api/db.json"
Use classes for that

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/services/apiUser.services.tsx
> +  axios.defaults.headers.common['Authorization'] = `Bearer ${token}`;
Code duplicates, you can extend your `BaseService` to `AuthService` and attach token to the requests

2021-12-08 14:11 UTC, CodeGeneration-2020 commented on mobile/src/services/helpers/asynsStorage.tsx
> +  async set(token: string) {
Create service with class

2021-12-09 09:10 UTC, 13dds13 commented on mobile/src/components/todoForm/TodoForm.tsx
> +          {errors.description && touched.description ? (
done

2021-12-09 09:10 UTC, 13dds13 commented on mobile/src/components/todoForm/TodoForm.tsx
> +            onValueChange={handleChange('priority')}
done

2021-12-09 09:10 UTC, 13dds13 commented on mobile/src/components/todoList/TodoList.tsx
> +    const { data } = useQuery('todos', apiTodosServices.getAllTodos);
fixed

2021-12-09 09:10 UTC, 13dds13 commented on mobile/src/components/todoList/todoItem/TodoItem.tsx
> +            queryClient.invalidateQueries('deletedTodo');
fixed

2021-12-09 09:11 UTC, 13dds13 commented on mobile/src/screens/EditTodoScreen.tsx
> +            queryClient.invalidateQueries('updatedTodo');
fixed

2021-12-09 09:12 UTC, 13dds13 commented on mobile/src/screens/RegisterScreen.tsx
> +                        <TextInput
fixed

2021-12-09 09:12 UTC, 13dds13 commented on mobile/src/screens/LoginScreen.tsx
> +                        <TextInput
fixed

2021-12-09 13:19 UTC, 13dds13 commented on mobile/src/services/apiTodosServices.tsx
> +import { endpoint } from "../../data/api/db.json"
done

2021-12-09 13:19 UTC, 13dds13 commented on mobile/src/services/apiUser.services.tsx
> +  axios.defaults.headers.common['Authorization'] = `Bearer ${token}`;
done

2021-12-09 13:20 UTC, 13dds13 commented on mobile/src/services/helpers/asynsStorage.tsx
> +  async set(token: string) {
done

2021-12-09 14:20 UTC, CodeGeneration-2020 requested changes

2021-12-09 14:20 UTC, CodeGeneration-2020 commented on mobile/src/services/apiServices/ApiService.tsx
> +export default class ApiService extends StorageService {
Do not extend that via StorageService, it is fully wrong abstraction

2021-12-09 14:36 UTC, 13dds13 commented on mobile/src/services/apiServices/ApiService.tsx
> +export default class ApiService extends StorageService {
fixed

2021-12-09 14:38 UTC, CodeGeneration-2020 approved these changes

2021-12-09 14:38 UTC, merged