feat: crud 'todo' backend
CodeGeneration-2020/CGS-test-camp-task pull request #48
Opened 2021-08-24 14:15 UTC by carrymisss

2021-08-25 05:18 UTC, CodeGeneration-2020 requested changes

2021-08-25 05:18 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +        const errors = validationResult(req);
Create error class for that 

```
interface IResponse {
  status(status: number): any;
  send(data: any): any;
}

class ResponseError {
error = {
  status: 0,
  message: 'not-seted'
}
constructor(private response: IResponse) {}

buildInternalServerError() {
  this.error = {
    status: 500,
    message: 'Server Error'
  }
  return this;
};
execute() {
 return this.response.send(this.error.status).send(this.error.message);
}
}
```

2021-08-25 05:18 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +            console.error(error);
Error class

2021-08-25 05:18 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +                res.status(HttpStatusCodes.OK).send("Todo item is updated.")
Error Class

2021-08-25 05:18 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +        } catch (error) {
To much checks for emptiness. on at the beginning will be enough and better to move that to error class

2021-08-25 05:18 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +            res.status(HttpStatusCodes.INTERNAL_SERVER_ERROR).send("Server Error");
Error class

2021-08-25 05:18 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +                    .json({ msg: "Todo not found" });
Error class

2021-08-25 05:18 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +                return res
Wrong error status, should be not found

2021-08-25 05:18 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +            } else {
Error class

2021-08-25 05:18 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +            console.error(err.message);
Error class

2021-08-25 05:18 UTC, CodeGeneration-2020 commented on server/src/controllers/user.controller.ts
> +            res.send("Place your register implementation here");
Error class

2021-08-25 05:18 UTC, CodeGeneration-2020 commented on server/src/middlewares/profile.middleware.ts
> +export default [
Create Validation Factory class

class ValidationFactory {
 createValidator1() {
   return []
 }
}

2021-08-25 07:28 UTC, CodeGeneration-2020 requested changes

2021-08-25 07:28 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +            let newTodo = await this.todoService.createTodo('6124e8f2f4f920350c5e5379', todoFields);
Static id in creation

2021-08-25 11:31 UTC, carrymisss commented on server/src/controllers/todo.controller.ts
> +            let newTodo = await this.todoService.createTodo('6124e8f2f4f920350c5e5379', todoFields);
I'll fix it later

2021-08-30 07:48 UTC, CodeGeneration-2020 requested changes

2021-08-30 07:48 UTC, CodeGeneration-2020 commented on server/src/factories/validators.factory.ts
> +    static auth = [
Используй методы а не поля

2021-08-30 07:48 UTC, CodeGeneration-2020 commented on server/src/factories/validators.factory.ts
> +    static todo = [
Используй методы а не поля

2021-08-30 07:48 UTC, CodeGeneration-2020 commented on server/src/factories/responses.factory.ts
> +            result.save();
Твой метод не должен ничего сейвить ты же просто делаешь валидацию

2021-08-30 07:48 UTC, CodeGeneration-2020 commented on server/src/factories/responses.factory.ts
> +    async updateResponse(serviceFunc: any, updateFunc: any) {
Упрости код, сделай что-то по типу такого

```javascript
class ResponseFactory {
async checkForExistance(entity) {
   const record = await entity.find();
   if(!record) {
                this.code = HttpStatusCodes.NOT_FOUND;
                return res.send("Todo doesn't exist.");
   }
   return this
}
async execute(command) {
    try {
    this.command();
    } catch(e) {
    this.internalServerError(error);
    }
     
}
}

```

Как использовать: 

```
controllerMethod(req, res) {
const reponseFactory = new ResponseFactory(res);

return reponseFactory.checkForExistance(Todo).execute(this.service.doSomething())
}
```

2021-09-02 15:05 UTC, CodeGeneration-2020 approved these changes

2021-09-02 15:05 UTC, merged