Feature/ablan abkenov/crud operations frontend
CodeGeneration-2020/CGS-test-camp-task pull request #53
Opened 2021-08-30 12:40 UTC by abkenov

Created components for CRUD operations for Todos, and some authorization components
Forms created with Formik, Validation conducted with Yup, Fetching done by React Query, Requests are in a separate class

Some issues with TS, could not assign type for destructured props
interface design is to be improved

2021-08-30 17:30 UTC, CodeGeneration-2020 requested changes
- Please configure `ESlint` for all the files all over the app
- Always avoid inline functions. Everything should be named, always
- Do not heep 2 components, logical functions into 1 file. Separate as much as you can in order to increase readability

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/App.tsx
>  import React from 'react';
this import should go first

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/App.tsx
> +          {/* <Authorization /> */}
remove commented code

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/App.tsx
> +    // alignItems: 'center',
remove commented code

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/EditTodo.tsx
> +  const validationSchema = yup.object().shape({
please move validation schemas to a separate file

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/Registration.tsx
> +        initialValues={
can we move it to a separate and `REUSABLE` object? theoretically

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/Registration.tsx
> +            onPress={() => {
please avoid inline functions. everything should be named

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/SignIn.tsx
> +        onSubmit={values => console.log(values)}
what is the purpose of `console.log` here? remove it

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/SignIn.tsx
> +        initialValues={
can we move it to a separate and `reusable` object?

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/SignIn.tsx
> +import { Button, SafeAreaView, StyleSheet, Text, TextInput, ScrollView, KeyboardAvoidingView, TouchableWithoutFeedback, Keyboard, Platform } from 'react-native';
this string is too long. please distribute imports into several lines

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/SignIn.tsx
> +            onPress={() => handleSubmit()}
please avoid inline functions. everything should be named

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/SignIn.tsx
> +            onPress={() => navigation.push('Registration')}
please avoid inline functions. everything should be named

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/Tabs.tsx
> +              onPress={() => navigation.navigate('CreateTodoScreen')}
please avoid inline functions. everything should be named

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/Tabs.tsx
> +        <Tab.Screen name="Todos" component={TodoContainerStackScreen} options={{headerShown: false}} />
spacings between curly braces

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/TodoContainer.tsx
> +const TodoElement = ({title, description, id, date, isCompleted, isPublic, navigation}) => {
spacings between curly braces

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/TodoContainer.tsx
> +      <Button title={'edit'} onPress={() => navigation.push('EditTodoScreen', {id: id})}></Button>
please avoid inline functions. everything should be named

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/TodoContainer.tsx
> +      <Button title={'delete'} onPress={() => todo_service.deleteTodoById(id)}></Button>
please avoid inline functions. everything should be named

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/TodoContainer.tsx
> +export default function TodoContainer({ navigation }) {
I would avoid having 2 different components into 1 file?
please always try to separate your business logic into some consolidated modules

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/TodoContainer.tsx
> +  console.log(data)
remove it

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/TodoContainer.tsx
> +  const renderItem = ( {item} : {item: any} ) => {
spacings between curly braces are missed

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on mobile/components/TodoElement.tsx
> +    <>
we can avoid having `<>` here at all, I believe

2021-08-30 17:30 UTC, CodeGeneration-2020 commented on server/src/routes/api/todos.route.ts
> +
redundant line

2021-08-30 18:26 UTC, abkenov commented on mobile/components/CreateTodo.tsx
> +            disabled={!isValid || !dirty}
It's a defined prop from Formik API, it checks if our form has been touched or not

2021-08-31 07:19 UTC, CodeGeneration-2020 requested changes
- Inline functions still exist
- Some props are handled incorrectly
- Always leave comments for potentially problematic parts of the code

2021-08-31 07:19 UTC, CodeGeneration-2020 commented on mobile/components/CreateTodo.tsx
> +      onSubmit={values => {
```
const onFormSubmit = () => {
   toDoService.createNewTodo(values)
   navigation.navigate('TodoContainer')
}
```

&& 

```
onSubmit={onFormSubmit}
```

2021-08-31 07:19 UTC, CodeGeneration-2020 commented on mobile/components/CreateTodo.tsx
> +      onSubmit={values => {
Everything should be named!

2021-08-31 07:19 UTC, CodeGeneration-2020 commented on mobile/components/CreateTodo.tsx
> +            disabled={!isValid || !dirty}
@abkenov leave comments in order to explain it

2021-08-31 07:19 UTC, CodeGeneration-2020 commented on mobile/components/CreateTodo.tsx
> +              onPress={() => toggleIsPublic(values)}>
inline function

2021-08-31 07:19 UTC, CodeGeneration-2020 commented on mobile/components/CreateTodo.tsx
> +              onPress={() => toggleIsCompleted(values)}>
inline function

2021-08-31 07:19 UTC, CodeGeneration-2020 commented on mobile/components/EditTodo.tsx
> +      onSubmit={values => {
inline function

2021-08-31 07:19 UTC, CodeGeneration-2020 commented on mobile/components/EditTodo.tsx
> +            <BouncyCheckbox onPress={() => toggleIsCompleted(values)}></BouncyCheckbox>
please avoid inline functions. everything should be named

2021-08-31 07:19 UTC, CodeGeneration-2020 commented on mobile/components/EditTodo.tsx
> +            <BouncyCheckbox onPress={() => toggleIsPublic(values)}></BouncyCheckbox>
please avoid inline functions. everything should be named

2021-08-31 07:19 UTC, CodeGeneration-2020 commented on mobile/components/Registration.tsx
> +        onSubmit={values => {}}
?? what is this?

2021-08-31 07:19 UTC, CodeGeneration-2020 commented on mobile/components/SignIn.tsx
> +        onSubmit={values => {}}
?

2021-09-13 14:06 UTC, closed without merging