Implement-CRUD back-end
CodeGeneration-2020/CGS-test-camp-task pull request #72
Opened 2022-01-17 13:56 UTC by VIKTORIAIT

2022-01-18 14:32 UTC, CodeGeneration-2020 requested changes

2022-01-18 14:32 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +    res.send(todos);
Handle res send inside tryCatch middleware

2022-01-18 14:32 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +  async editTodoItem(_: Request, res: Response) {
Add request body and params types

2022-01-18 14:32 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +  async editTodoItem(_: Request, res: Response) {
Add isExistMiddleware

2022-01-18 14:32 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +  async deleteTodoItem(_: Request, res: Response) {
Types

2022-01-18 14:32 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +  async deleteTodoItem(_: Request, res: Response) {
Add isExistMiddleware

2022-01-18 14:32 UTC, CodeGeneration-2020 commented on server/src/controllers/todo.controller.ts
> +    console.log(todos, "todoooos");
Console log

2022-01-18 19:56 UTC, VIKTORIAIT commented on server/src/controllers/todo.controller.ts
> +    res.send(todos);
Ok, thanks

2022-01-19 08:50 UTC, VIKTORIAIT commented on server/src/controllers/todo.controller.ts
> +    console.log(todos, "todoooos");
Ok

2022-01-24 06:49 UTC, closed without merging