feat: crud frontend
CodeGeneration-2020/CGS-test-camp-task pull request #73
Opened 2021-09-06 13:37 UTC by Bodya13

created a folder src with all components

2021-09-06 14:16 UTC, CodeGeneration-2020 requested changes
- Please keep applying `ESlint` all over the app
- Try to not use `let` and `function` keywords, you can do code without it in 99.9% of cases
- Please consider moving complex logic into separate functions / modules in order to increase readability
- Do not use inline styles, everything should be named
- Do not use inline functions, everything should be named
- Whenever you have a complex logic (for instance just like you have in some of your `useEffect` functions - consider moving it into separate functions)

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoCreate.js
> +                                // checkedIcon={<Image source={require('../checked.png')}/>}
please remove commented code here

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoCreate.js
> +                                containerStyle={{margin: 0, padding: 0}}
get rid of inline styles here and move it to a separate function
also is not `containerStyle` here has `margin` and `padding` set to 0 by default?

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoCreate.js
> +                                onPress={() => {
please get rid of inline function. everything should be named

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoCreate.js
> +                                // checkedIcon={<Image source={require('../checked.png')}/>}
please remove commented code here

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoCreate.js
> +                                containerStyle={{margin: 0, padding: 0}}
get rid of inline styles here and move it to a separate function
also is not containerStyle here has margin and padding set to 0 by default?

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoCreate.js
> +                                    values.isCompleted = !isCompleted;
this is a wrong practice. never change values directly. there is a dedicated method for it!

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoCreate.js
> +                            <Text style={{textAlign: "center"}}>Create</Text>
inline styles

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoEdit.js
> +                onSubmit={values => {
get rid of inline styles here and move it to a separate function
also is not containerStyle here has margin and padding set to 0 by default?

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoEdit.js
> +                                onPress={() => {
get rid of inline styles here and move it to a separate function
also is not containerStyle here has margin and padding set to 0 by default?

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoEdit.js
> +                                containerStyle={{margin: 0, padding: 0}}
get rid

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoEdit.js
> +                                // checkedIcon={<Image source={require('../checked.png')}/>}
remove commented code here please

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoEdit.js
> +                            <Text style={{textAlign: "center"}}>Edit</Text>
inline styles

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoEntrance.js
> +                style={[styles.button, {marginBottom: 20}]}
inline styles. remove

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoItem.js
> +                <View style={{flexDirection: "row"}}>
inline styles

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoItem.js
> +            <View style={{width: "70%"}}>
inline styles

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoItem.js
> +            <View style={{width: "25%", flexDirection: "row", justifyContent: "space-between"}}>
inline styles

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoItem.js
> +                <View style={{flexDirection: "row"}}>
inline styles

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoItem.js
> +                    style={{alignItems: "center"}}
inline styles

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoItem.js
> +                    style={{alignItems: "center"}}
inline styles

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoItem.js
> +                            uri: "https://icons-for-free.com/iconfiles/png/512/draw+edit+pen+pencil+text+write+icon-1320162307919760358.png"
can you move it to a separate, reusable constant

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoItem.js
> +                            uri: "http://cdn.onlinewebfonts.com/svg/img_377999.png"
can you move it to a separate, reusable constant

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +import React, {useState, useEffect } from "react";
please keep spacings between curly braces

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +import {TodoService} from "../service/todo.service"
please keep spacings between curly braces

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +export default function TodoPage({route, navigation}) {
please keep spacings between curly braces

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +        async function getMyTodos() {
`function` keyword is redundant here. use arrow functions, always

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +            async function createMyTodo() {
the same here

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +            async function createMyTodo() {
can we also move logic from all the `useEffect`'s you have into separate functions?

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +            async function uptadeMyTodo() {
the same here, please use arrow functions

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +        let newTodos = todos;
is there a reason you use `let` here and why to not use `todos` variable?

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +                style={{width: "100%"}}
remove inline styles

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +                onPress={() => onPressCreate()}
move the inline function to a named one

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +                        onpressEdit={(todo) => onPressEdit(todo)}
is there a reason we use inline function here?
`onPressEdit={onPressEdit}` this will also work :)

Also please do JS naming, we follow camelCase, so instead of `onpressEdit` => do `onToDoPressEdit`

2021-09-06 14:16 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +                        onpressDelete={(todo) => onPressDelete(todo)}
the same as above

2021-09-07 06:46 UTC, Bodya13 commented on mobile/src/TodoPage.js
> +        let newTodos = todos;
todos is a state variable, so I can`t change it directly

2021-09-07 11:28 UTC, CodeGeneration-2020 requested changes
Much better, but still requires some fundamental changes.
For more explanation ping me in PM

2021-09-07 11:28 UTC, CodeGeneration-2020 commented on mobile/src/TodoContainer.js
> +import 'react-native-gesture-handler';
why do use single quotes here and double quotes below?

2021-09-07 11:28 UTC, CodeGeneration-2020 commented on mobile/src/TodoContainer.js
> +import React from "react";
this should go as a first import, always

2021-09-07 11:28 UTC, CodeGeneration-2020 commented on mobile/src/TodoContainer.js
> +import { View, StyleSheet } from "react-native";
and this as a second one

2021-09-07 11:28 UTC, CodeGeneration-2020 commented on mobile/service/todo.service.ts
> +const URL = 'http://localhost:5000/api';
I think, `BASE_URL` is better naming here
`URL` is kind of an abstract, isn't it?

2021-09-07 11:28 UTC, CodeGeneration-2020 commented on mobile/src/TodoContainer.js
> +                    options={ {title: 'Home'} }
not really, I meant `options={{ title: 'Home' }}`

2021-09-07 11:28 UTC, CodeGeneration-2020 commented on mobile/src/TodoContainer.js
> +                    options={ {title: 'Creating'} }
the same here

2021-09-07 11:28 UTC, CodeGeneration-2020 commented on mobile/src/TodoContainer.js
> +                    options={ {title: 'Editing'} }
the same here

2021-09-07 11:28 UTC, CodeGeneration-2020 commented on mobile/src/TodoCreate.js
> +        <View style={ styles.createContainer }>
Bohdana, you should only do spacings between curly braces, whenever you declare an object. whether it is inside jsx property declaration or something.
Having spacings between curly braces, while declaring a property - is a wrong practice :)
Please return it back

2021-09-07 11:28 UTC, CodeGeneration-2020 commented on mobile/src/TodoCreate.js
> +                onSubmit={values => onSubmitData(values) }
can we do named function here?

2021-09-07 11:28 UTC, CodeGeneration-2020 commented on mobile/src/TodoEdit.js
> +import { CheckBox } from 'react-native-elements'
is there a reason we use single quotes above and double quotes here?

2021-09-07 11:28 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +        let newTodos = todos;
@Bodya13 this logic is a bit wrong.
whenever you do `let newTodos = todos` you still change the state directly, because you do assign by a link here
to avoid it - better do `let newTodos = [...todos];` that means, that you basically declare a new variable.
Furthermore. whenever you do `.map` it automatically returns new array (check JS docs for .map, .filter, .reduce methods). so this `let` expression is redundant here

also can you move `updateMyToDo` function to a separate file and work with data through the arguments?

one more thing, I honestly do not see a reason, why do to this expression here
why to not just do:

2021-09-07 11:28 UTC, CodeGeneration-2020 commented on mobile/src/TodoPage.js
> +            setTodos([...newTodos])
you can just do `setTodos(newTodos)` :)

2021-09-07 17:05 UTC, CodeGeneration-2020 requested changes
Bohdana, please configure `ESlint` and run in through the whole app
open each file and configure it via `ESlint`

2021-09-07 17:05 UTC, CodeGeneration-2020 commented on mobile/src/TodoContainer.js
> +})
missed trailing coma

2021-09-07 17:05 UTC, CodeGeneration-2020 commented on mobile/src/TodoEntrance.js
> +                style={ [styles.button, styles.login] }
redundant spacings here

2021-09-08 11:29 UTC, merged