feat: Todo list - CRUD operations on backend
CodeGeneration-2020/CGS-test-camp-task pull request #96
Opened 2021-09-21 09:38 UTC by starklast

feat: Todo list - CRUD operations on backend

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/controllers/todo.controller.ts
> +type reqBody = {
Используй реквест тип который есть в экспресе

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/controllers/todo.controller.ts
> +    async getTodo(req: Request & { params: { id: string } }, res: Response) {
Странный тип 
используй дженерик

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/controllers/todo.controller.ts
> +    async addTodo(req: reqBody, res: Response, next: NextFunction) {
Используй реквест

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/controllers/todo.controller.ts
> +    async addTodo(req: reqBody, res: Response, next: NextFunction) {
експреса

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/controllers/todo.controller.ts
> +import iTodo from "../types/Todo";
I должно быть с большой

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/controllers/todo.controller.ts
> +import iTodo from "../types/Todo";
Название типа с маленькой

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/controllers/todo.controller.ts
> +            const errors = validationResult(req);
Вынести это в валидатор класс чтоб не дублировать код в каждом твоем методе конроллера

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/controllers/todo.controller.ts
> +            if (!errors.isEmpty()) {
Вынести это в валидатор класс чтоб не дублировать код в каждом твоем методе конроллера

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/controllers/todo.controller.ts
> +    async deleteTodo(req: reqBody, res: Response, next: NextFunction) {
Тип

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/controllers/todo.controller.ts
> +        const data = { ...req.body };
Зачем здесь спред ?

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/controllers/todo.controller.ts
> +        const data = { ...req.body };
Зачем здесь спред ?

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/routes/api/todos.route.ts
> +todosRouter.post("",
Вынеси валидаторы в класс Validator и используй их как методы ПСЕВДОКОД createValidatorTodo()

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/routes/api/todos.route.ts
> +    check("title", "todo should contain title").not().isEmpty(),
Дублирование логики

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/services/todo.service.ts
> +        const todo = await Todo.findByIdAndUpdate(_id, data as UpdateQuery<ITodo>);
Странный тип

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/services/todo.service.ts
> +        const { _id } = { ...data };
Зачем ты спредишь ?

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/services/todo.service.ts
> +        const todo = await Todo.create({ ...data });
Зачем ты спредишь ?

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/services/todo.service.ts
> +        const { _id } = { ...data };
Зачем ты спредишь ?

2021-09-21 15:35 UTC, DanyylKuchkovInbev commented on server/src/controllers/todo.controller.ts
> +            const errors = validationResult(req);
+ добавь проверку на существование для апдейт и делит

2021-09-21 18:35 UTC, starklast commented
внес исправления по всем замечаниям.

2021-09-23 12:49 UTC, CodeGeneration-2020 requested changes

2021-09-23 12:49 UTC, CodeGeneration-2020 commented on server/src/services/todo.service.ts
> +        const todo = await Todo.findByIdAndUpdate(_id, data as ITodo);
as здесь лишний

2021-09-23 14:33 UTC, merged